[phases.setup]
nixPkgs = ["python3", "gcc", "python38Packages.pip"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn dana.wsgi:application --log-file -"