# Generated by Django 4.2.4 on 2025-04-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='counter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='dana_app.counter'),
        ),
    ]
