# Generated by Django 4.2.4 on 2025-04-10 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dana_app', '0002_member_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='miqaat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dana_app.miqaat'),
        ),
        migrations.AlterField(
            model_name='member',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dana_app.zone'),
        ),
    ]
