# Generated by Django 4.2.4 on 2025-04-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dana_app', '0003_alter_member_miqaat_alter_member_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='its',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
